version: '3'

volumes:
  postgres_data: {}
  postgres_backup: {}

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    environment:
      - POSTGRES_DB=ex_libris

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    depends_on:
      - postgres
      - redis
    command: /start-dev.sh
    env_file: .env
    volumes:
      - .:/app

  js:
    build:
      context: .
      dockerfile: ./compose/js/Dockerfile
    volumes:
      - ./client:/app

  nginx:
    build: ./compose/nginx
    depends_on:
      - django
      - js
    volumes:
      - ./client/build:/web
    ports:
      - "0.0.0.0:80:80"

  redis:
    image: redis:3.0
